[build]
  command = "npm run build"
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    baseUrl = "https://marilyns-windows.netlify.app/"
    urlPrefix = "/"
