[[redirects]]
from = "https://marilyns-windows.netlify.app/*"
to = "https://<marilynswindows.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://marilyns-windows.netlify.app/*"
to = "https://<marilynswindows.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://marilyns-windows.netlify.com/*"
to = "https://<marilynswindows.com/:splat"
status = 301
force = true